### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [keyfour/BlueDemanApp#1]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by keyfour** [comment]
No problem! Do it if you want :+1:

**Comment by mansya** [comment]
I have designed the logo for this project. What do you think ? do you like it ? if yes let me know and if there are changes please let me know.
![portofolio](https://user-images.githubusercontent.com/33461607/48490616-64296280-e858-11e8-98bb-0ebad426305d.png)

**Comment by keyfour** [comment]
Wow, looks great! I like #1 more than others. But all of then very nice.

**Comment by mansya** [comment]
I have sent you [**pull requests.**](https://github.com/keyfour/BlueDemanApp/pull/2) please check. and I have also uploaded all files to the drive. [**Download**](https://drive.google.com/open?id=11EKUsI7L1WX2yOmX4oNST6gPAYEeFs8_)
